-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS users
(
    user_id bigint NOT NULL,
    user_birthday text NOT NULL,
    user_height integer NOT NULL,
    user_weight double precision NOT NULL,
    user_fitness_target text NOT NULL,
    user_sex boolean NOT NULL,
    user_hypertain text NOT NULL,
    user_diabet text NOT NULL,
    user_level smallint,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS fitness
(
    fitness_id serial NOT NULL,
    user_id bigint NOT NULL,
    fitness_date date NOT NULL,
    fitness_train text NOT NULL,
    PRIMARY KEY (fitness_id)
);

CREATE TABLE IF NOT EXISTS dishes
(
    dishes_id serial NOT NULL,
    user_id bigint NOT NULL,
    dishes_name text NOT NULL,
    dishes_num smallint NOT NULL,
    dishes_date date NOT NULL,
    PRIMARY KEY (dishes_id)
);

CREATE TABLE IF NOT EXISTS pictures
(
    picture_title text NOT NULL,
    picture_description text NOT NULL,
    picture_link text NOT NULL,
    PRIMARY KEY (picture_title)
);

ALTER TABLE IF EXISTS fitness
    ADD FOREIGN KEY (user_id)
    REFERENCES users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS dishes
    ADD FOREIGN KEY (user_id)
    REFERENCES users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;