-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS fitness;
DROP TABLE IF EXISTS fitness_share;
DROP TABLE IF EXISTS dishes;
DROP TABLE IF EXISTS pictures;
DROP EXTENSION IF EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS dishes
(
    dish_id serial PRIMARY KEY,
    dish_time text not null, 
    dish_title text NOT NULL,
    dish_kcal float NOT NULL CHECK (dish_kcal >= 0),
    dish_proteins float NOT NULL CHECK (dish_proteins >= 0),
    dish_fats float NOT NULL CHECK (dish_fats >= 0),
    dish_carbs float NOT NULL CHECK (dish_carbs >= 0),
    dish_desc text not null
);

CREATE TABLE IF NOT EXISTS recipes
(
    dish_id bigint not null,
    recipe_order int not null CHECK (recipe_order > 0),
    recipe_instruct text NOT NULL,
    recipe_img text
);

ALTER TABLE IF EXISTS recipes
    ADD FOREIGN KEY(dish_id)
    REFERENCES dishes(dish_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

CREATE TABLE IF NOT EXISTS training
(
    training_id SERIAL PRIMARY KEY,
    training_title text NOT NULL,
    training_desc text NOT NULL,
    training_user_level int not null CHECK(training_user_level > 0)
);

create table if not exists training_instr
(
    training_id bigint not null,
    training_order int not null check (training_order > 0),
    training_instr text not null,
    training_img text
);

ALTER TABLE IF EXISTS training_instr
    ADD FOREIGN KEY(training_id)
    REFERENCES training(training_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

create table if not exists diet_plan
(
    dish_id bigint not null,
    user_id bigint not null,
    dish_weight float not null check (dish_weight > 0),
    date text NOT NULL
);

ALTER TABLE IF EXISTS diet_plan
    ADD FOREIGN KEY(dish_id)
    REFERENCES dishes(dish_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS diet_plan
    ADD FOREIGN KEY(user_id)
    REFERENCES users(user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

create table if not exists train_plan
(
    training_id bigint not null,
    user_id bigint not null,
    date text NOT NULL
);

ALTER TABLE IF EXISTS train_plan
    ADD FOREIGN KEY(training_id)
    REFERENCES training(training_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS train_plan
    ADD FOREIGN KEY(user_id)
    REFERENCES users(user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

create table if not exists weight_hist
(
    user_id bigint not null,
    weight float not null check (weight > 0),
    date text not null
);

ALTER TABLE IF EXISTS weight_hist
    ADD FOREIGN KEY(user_id)
    REFERENCES users(user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;