services:
  
  fitness_service:
    container_name: fitness_service
    build:
      context: ./fitness_service
      dockerfile: dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=0000
      - DB_NAME=grpc_fitness_db
      - GRPC_PORT=14500
      - GRPC_TIMEOUT=24h
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    ports:
      - 14500:14500
    networks:
      - grpc_network
      - db_network
  db:
    container_name: fitness_db
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=grpc_fitness_db
    volumes:
      - db_data:/var/lib/postgresql/db_data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    networks:
      - db_network
  
  migrator:
    container_name: migrator_fitness
    build:
      context: ./db
      dockerfile: dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=0000
      - DB_NAME=grpc_fitness_db
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - db_network

volumes:
  db_data:

networks:
  grpc_network:
    external: true
  db_network:
    driver: bridge
